# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
    paths: ["src/**"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, closed]
    paths: ["src/**"]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ../src/global.json

    - name: Cache NuGet Packages
      id: nuget-packages
      uses: actions/cache@v3
      env:
        cache-name: nuget-package-cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ env.cache-name }}
          
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
